
import { Course, Language } from './types';

export const UI_TEXT = {
  en: {
    welcome: "BridgeEd Premium",
    tagline: "Bridging Worlds through Knowledge",
    switchRegion: "Switch Region",
    forum: "Multilingual Forum",
    courses: "My Learning",
    aiTutor: "AI Tutor",
    translate: "Translate",
    explore: "Catalog",
    westTitle: "Western Perspective",
    arabTitle: "Arab World Perspective",
    criticalThinking: "Focus: Critical Thinking",
    localValues: "Focus: Local Values",
    chatPlaceholder: "Ask your AI Tutor...",
    enroll: "Enroll Now",
    enrolled: "Enrolled",
    unenroll: "Unenroll",
    emptyLearning: "Start your journey today!",
    startLearning: "Resume",
    practice: "AI Practice",
    grading: "Evaluating...",
    getGrade: "Check Answer",
    next: "Next Question",
    subscription: "Subscription",
    upgrade: "Upgrade to Pro",
    proStatus: "PRO Access",
    freeStatus: "Free Tier",
    difficulty: "Difficulty",
    duration: "Duration",
    login: "Log In",
    signup: "Sign Up",
    email: "Email Address",
    password: "Password",
    fullName: "Full Name",
    logout: "Sign Out",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    authSubtitle: "Access your global learning dashboard",
    createAccount: "Create your Account",
    selectTier: "Select your Plan"
  },
  fr: {
    welcome: "BridgeEd Premium",
    tagline: "Relier les Mondes par le Savoir",
    switchRegion: "Changer de Région",
    forum: "Forum Multilingue",
    courses: "Mon Apprentissage",
    aiTutor: "Tuteur IA",
    translate: "Traduire",
    explore: "Catalogue",
    westTitle: "Perspective Occidentale",
    arabTitle: "Perspective Monde Arabe",
    criticalThinking: "Focus: Esprit Critique",
    localValues: "Focus: Valeurs Locales",
    chatPlaceholder: "Posez une question...",
    enroll: "S'inscrire",
    enrolled: "Inscrit",
    unenroll: "Se désinscrire",
    emptyLearning: "Commencez votre voyage !",
    startLearning: "Reprendre",
    practice: "Exercice IA",
    grading: "Évaluation...",
    getGrade: "Vérifier",
    next: "Question Suivante",
    subscription: "Abonnement",
    upgrade: "Passer à Pro",
    proStatus: "Accès PRO",
    freeStatus: "Niveau Gratuit",
    difficulty: "Difficulté",
    duration: "Durée",
    login: "Se connecter",
    signup: "S'inscrire",
    email: "Adresse Email",
    password: "Mot de passe",
    fullName: "Nom Complet",
    logout: "Déconnexion",
    noAccount: "Pas de compte ?",
    hasAccount: "Déjà un compte ?",
    authSubtitle: "Accédez à votre tableau de bord",
    createAccount: "Créer votre compte",
    selectTier: "Choisissez votre plan"
  },
  ar: {
    welcome: "BridgeEd المميز",
    tagline: "جسر العوالم عبر المعرفة",
    switchRegion: "تغيير المنطقة",
    forum: "المنتدى",
    courses: "تعليمي",
    aiTutor: "المعلم الذكي",
    translate: "ترجمة",
    explore: "كتالوج",
    westTitle: "المنظور الغربي",
    arabTitle: "منظور العالم العربي",
    criticalThinking: "التركيز: التفكير النقدي",
    localValues: "التركيز: القيم المحلية",
    chatPlaceholder: "اسأل معلمك...",
    enroll: "سجل الآن",
    enrolled: "تم التسجيل",
    unenroll: "إلغاء التسجيل",
    emptyLearning: "ابدأ رحلتك اليوم!",
    startLearning: "استكمال",
    practice: "تدريب الذكاء الاصطناعي",
    grading: "تقييم...",
    getGrade: "تحقق من الإجابة",
    next: "السؤال التالي",
    subscription: "الاشتراك",
    upgrade: "ترقية إلى PRO",
    proStatus: "وصول PRO",
    freeStatus: "المستوى المجاني",
    difficulty: "الصعوبة",
    duration: "المدة",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    fullName: "الاسم الكامل",
    logout: "تسجيل الخروج",
    noAccount: "ليس لديك حساب؟",
    hasAccount: "لديك حساب بالفعل؟",
    authSubtitle: "الوصول إلى لوحة التعلم العالمية الخاصة بك",
    createAccount: "إنشاء حسابك",
    selectTier: "اختر خطتك"
  }
};

export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    title: { en: 'Logic and Argumentation', fr: 'Logique et Argumentation', ar: 'المنطق والمناظرة' },
    description: { en: 'Advanced critical thinking and debate structures using Socratic methods.', fr: 'Pensée critique avancée et structures de débat utilisant les méthodes socratiques.', ar: 'التفكير النقدي المتقدم وهياكل المناظرة باستخدام الطرق السقراطية.' },
    category: 'humanities',
    region: ['west'],
    thumbnail: 'https://picsum.photos/seed/logic/400/300',
    difficulty: 'intermediate',
    duration: '12h'
  },
  {
    id: '2',
    title: { en: 'Golden Age Science', fr: 'L\'Âge d\'Or des Sciences', ar: 'العلوم في العصر الذهبي' },
    description: { en: 'Contributions of Arab scholars to modern physics and chemistry.', fr: 'Contributions des savants arabes à la physique et chimie modernes.', ar: 'مساهمات العلماء العرب في الفيزياء والكيمياء الحديثة.' },
    category: 'science',
    region: ['arab'],
    thumbnail: 'https://picsum.photos/seed/science/400/300',
    difficulty: 'beginner',
    duration: '8h'
  },
  {
    id: '3',
    title: { en: 'Modern Algebra', fr: 'Algèbre Moderne', ar: 'الجبر الحديث' },
    description: { en: 'From Al-Khwarizmi to modern quantum computing and cryptography.', fr: 'D\'Al-Khwarizmi à l\'informatique quantique et cryptographie moderne.', ar: 'من الخوارزمي إلى الحوسبة الكمومية الحديثة والتشفير.' },
    category: 'tech',
    region: ['arab', 'west'],
    thumbnail: 'https://picsum.photos/seed/math/400/300',
    difficulty: 'advanced',
    duration: '20h'
  },
  {
    id: '4',
    title: { en: 'Ethics of AI', fr: 'Éthique de l\'IA', ar: 'أخلاقيات الذكاء الاصطناعي' },
    description: { en: 'Exploring global perspectives on machine learning morality.', fr: 'Explorer les perspectives mondiales sur la moralité de l\'apprentissage automatique.', ar: 'استكشاف المنظورات العالمية حول أخلاقيات التعلم الآلي.' },
    category: 'tech',
    region: ['west', 'arab'],
    thumbnail: 'https://picsum.photos/seed/ethics/400/300',
    difficulty: 'intermediate',
    duration: '15h'
  }
];
